<a href="https://colab.research.google.com/github/Amanyadav3A/Deep-Learning/blob/main/05_Backpropagation_1_algo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np
import pandas as pd

In [57]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [58]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for i in range(1,L):
    parameters['W'+str(i)] = np.ones((layer_dims[i-1],layer_dims[i]))*0.1
    parameters['b'+str(i)] = np.zeros((layer_dims[i],1))
  return parameters


In [59]:
def linear_forward(A_prev, W, b):
  z = np.dot(W.T, A_prev) + b
  return z

In [60]:
# forward propagation
def L_layer_forward(X, parameters):
  A = X
  L = len(parameters)//2   # number of layers in the neural networks

  for i in range(1, L+1):
    A_prev = A
    W = parameters['W'+str(i)]
    b = parameters['b'+str(i)]

    # print('A'+str(i-1)+':',A_prev)
    # print('W'+str(i)+':',W)
    # print('b'+str(i)+':',b)
    # print('-'*20)

    A = linear_forward(A_prev, W, b)
    # print('A'+str(i)+':',A)
    # print('*'*20)

  return A_prev, A


In [61]:
# updating the weights using gradient descent

def update_parameters(parameters, y, y_hat, A_prev, X, lr):

  new_parameters = parameters

  new_parameters['W2'][0][0] = parameters['W2'][0][0]+lr*2*(y-y_hat)*A_prev[0][0]
  new_parameters['W2'][1][0] = parameters['W2'][1][0]+lr*2*(y-y_hat)*A_prev[1][0]
  new_parameters['b2'][0][0] = parameters['b2'][0][0]+lr*2*(y-y_hat)

  new_parameters['W1'][0][0] = parameters['W1'][0][0]+lr*2*(y-y_hat)*parameters['W2'][0][0]*X[0][0]
  new_parameters['W1'][0][1] = parameters['W1'][0][1]+lr*2*(y-y_hat)*parameters['W2'][0][0]*X[1][0]
  new_parameters['b1'][0][0] = parameters['b1'][0][0]+lr*2*(y-y_hat)*parameters['W2'][0][0]

  new_parameters['W1'][1][0] = parameters['W1'][1][0]+lr*2*(y-y_hat)*parameters['W2'][1][0]*X[0][0]
  new_parameters['W1'][1][1] = parameters['W1'][1][1]+lr*2*(y-y_hat)*parameters['W2'][1][0]*X[1][0]
  new_parameters['b1'][1][0] = parameters['b1'][1][0]+lr*2*(y-y_hat)*parameters['W2'][1][0]

  return new_parameters

In [62]:
# training the model now
parameters = initialize_parameters([2,2,1])
parameters
epochs = 75
lr = 0.001

for i in range(epochs):
  avg_mse = 0
  for j in range(df.shape[0]):
    n = np.random.randint(0,df.shape[0])
    X = df[['cgpa','profile_score']].values[n].reshape(2,1)
    y = df[['lpa']].values[n][0]

    A, y_hat = L_layer_forward(X, parameters)
    parameters = update_parameters(parameters, y, y_hat[0][0], A, X, lr )

    avg_mse += (y - y_hat[0][0])**2
  print("epoch-",i+1,": loss :",avg_mse/df.shape[0])
  print('*'*40)

epoch- 1 : loss : 26.27944136202024
****************************************
epoch- 2 : loss : 10.099029260510786
****************************************
epoch- 3 : loss : 16.96025913366133
****************************************
epoch- 4 : loss : 2.504711312540378
****************************************
epoch- 5 : loss : 2.16579866359636
****************************************
epoch- 6 : loss : 1.3824423860752888
****************************************
epoch- 7 : loss : 0.8375338392471456
****************************************
epoch- 8 : loss : 0.3549583241100473
****************************************
epoch- 9 : loss : 1.4452937661036453
****************************************
epoch- 10 : loss : 0.9495905077887246
****************************************
epoch- 11 : loss : 1.270226375392814
****************************************
epoch- 12 : loss : 1.557412794514113
****************************************
epoch- 13 : loss : 1.6077537410319884
******************************

In [63]:
parameters

{'W1': array([[-0.02568136,  0.6978368 ],
        [-0.02286306,  0.81591523]]),
 'b1': array([[0.02434539],
        [0.03103254]]),
 'W2': array([[0.38460544],
        [0.46580356]]),
 'b2': array([[0.10366015]])}

In [64]:
y_pred = L_layer_forward([[7],[9]], parameters)[1]
y_pred

array([[5.675089]])

In [65]:
# now using keras
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [66]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [67]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [68]:
model.get_weights()

[array([[ 0.01480365,  1.0208207 ],
        [-0.6022599 ,  0.40950763]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.9592842],
        [ 1.1605285]], dtype=float32),
 array([0.], dtype=float32)]

In [69]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]], dtype=np.float32),
               np.array([0,0], dtype=np.float32),
               np.array([[0.1],[0.1]], dtype=np.float32),
               np.array([0], dtype=np.float32)]

In [70]:
model.set_weights(new_weights)

In [71]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [72]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [73]:
X = df[['cgpa','profile_score']].values
y = df[['lpa']].values

In [74]:
X,y

(array([[ 8,  8],
        [ 7,  9],
        [ 6, 10],
        [ 5, 12]]),
 array([[4],
        [5],
        [6],
        [7]]))

In [75]:
model.fit(X,y, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 27.8873  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.5591 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.2546 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.9101  
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.5461 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.2161 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25.8327 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.4327 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.0361 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24.6759 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24.2155 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.8130 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.3717 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 22.9334 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.5059 
Epoch 16/75
4/4 ━

In [76]:
model.get_weights()

[array([[0.37357596, 0.37357596],
        [0.36564744, 0.36564744]], dtype=float32),
 array([0.27230847, 0.27230847], dtype=float32),
 array([[0.37292916],
        [0.37292916]], dtype=float32),
 array([0.2047872], dtype=float32)]

In [77]:
model.predict(X)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[4.818738 ],
       [4.8128242],
       [4.806911 ],
       [5.0737185]], dtype=float32)